/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-04-29 05:34:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.days08;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex08_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1098678824000L));
    _jspx_dependants.put("jar:file:/C:/E/Sist/Class/Workspace/JSPClass/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jspPro/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"http://localhost/jspPro/images/SiSt.ico\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/jspPro/resources/cdn-main/example.css\">\r\n");
      out.write("<script src=\"/jspPro/resources/cdn-main/example.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(" span.material-symbols-outlined{\r\n");
      out.write("    vertical-align: text-bottom;\r\n");
      out.write(" }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("  <h1 class=\"main\"><a href=\"#\" style=\"position: absolute;top:30px;\">yeon HOme</a></h1>\r\n");
      out.write("  <ul>\r\n");
      out.write("    <li><a href=\"#\">로그인</a></li>\r\n");
      out.write("    <li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</header>\r\n");
      out.write("<h3>\r\n");
      out.write("  <span class=\"material-symbols-outlined\">view_list</span> jsp days00\r\n");
      out.write("</h3>\r\n");
      out.write("<div>\r\n");
      out.write("  <xmp class=\"code\">\r\n");
      out.write("    [프로젝트에 사용할 실제 예제 : jquery ajax 처리]\r\n");
      out.write("     jquery ajax 함수 : \r\n");
      out.write("      get 방식 - getJSON()[요청:GET/출력:JSON], getScript(), get()\r\n");
      out.write("      post 방식 - post()\r\n");
      out.write("      get/post 방식 - load()	[ $.ajax() ]\r\n");
      out.write("    \r\n");
      out.write("     회원가입\r\n");
      out.write("      id : [  ] [ID 중복체크 버튼] jquery -> ajax 처리\r\n");
      out.write("      ex08_idcheck.jsp\r\n");
      out.write("  </xmp>\r\n");
      out.write("  \r\n");
      out.write("  <h2>회원가입 페이지</h2>\r\n");
      out.write("  <form action=\"\" method=\"get\">\r\n");
      out.write("  	deptno : <input type=\"text\" name=\"deptno\" value=\"10\" /><br>\r\n");
      out.write("  	empno(id) : <input type=\"text\" name=\"empno\" value=\"7369\" />\r\n");
      out.write("  	<input type=\"button\" id=\"btnEmpnoCheck\" \r\n");
      out.write("  			value=\"empno 중복체크 - jquery ajax\" />\r\n");
      out.write("  	<p id=\"notice\"></p>\r\n");
      out.write("  	<br>\r\n");
      out.write("  	ename : <input type=\"text\" name=\"ename\" value=\"\" /><br>\r\n");
      out.write("  	job : <input type=\"text\" name=\"job\" value=\"\" /><br>\r\n");
      out.write("  	\r\n");
      out.write("  	<input type=\"submit\" value=\"회원(emp) 가입\" />  	\r\n");
      out.write("  	\r\n");
      out.write("  </form>  \r\n");
      out.write("   \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  $(function (){\r\n");
      out.write("	  $(\"#btnEmpnoCheck\").on(\"click\", function(){\r\n");
      out.write("		  // ajax params =   	?[empno=7369]\r\n");
      out.write("		  let params = $(\"form\").serialize();\r\n");
      out.write("		  //alert( params );\r\n");
      out.write("		  $.ajax({\r\n");
      out.write("			 url : \"ex08_idcheck.jsp\"\r\n");
      out.write("			 	, dataType : \"json\" // text, json, xml, jsonp 등등\r\n");
      out.write("			 	, type : \"GET\"\r\n");
      out.write("			 	, data : params\r\n");
      out.write("			 	, cache: false    // ***** 캐시 사용X (꼭 설정하기!!)\r\n");
      out.write("		  		, success: function(data, textStatus, jqXHR) {\r\n");
      out.write("		  			// {count:1}\r\n");
      out.write("		  			// jquery ajax 함수에서는 전달된 data JSON 데이터를\r\n");
      out.write("		  			// 자동으로 js 객체로 변환을 한다.\r\n");
      out.write("		  			// JSON.parse() json => js Object 변환할 필요가 없다.\r\n");
      out.write("		  			//alert( data.count );\r\n");
      out.write("		  			if( data.count == 1 ){\r\n");
      out.write("		  				$(\"#notice\").css(\"color\", \"red\").text(\"이미 사용 중인 ID 입니다.\");\r\n");
      out.write("		  			} else {\r\n");
      out.write("		  				$(\"#notice\").css(\"color\", \"black\").text(\"사용 가능한 ID 입니다.\");\r\n");
      out.write("		  			}\r\n");
      out.write("		  			\r\n");
      out.write("		  		} , error :function (){\r\n");
      out.write("		  			alert(\"에러~~~\");\r\n");
      out.write("		  		}\r\n");
      out.write("		  });\r\n");
      out.write("		  \r\n");
      out.write("	  }); // click\r\n");
      out.write("  }); // function\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
