/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-02 01:00:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1098678824000L));
    _jspx_dependants.put("jar:file:/C:/E/Sist/Class/Workspace/JSPClass/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jspPro/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"shortcut icon\" href=\"http://localhost/jspPro/images/SiSt.ico\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"/jspPro/resources/cdn-main/example.css\">\n");
      out.write("<script src=\"/jspPro/resources/cdn-main/example.js\"></script>\n");
      out.write("<style>\n");
      out.write(" span.material-symbols-outlined{\n");
      out.write("    vertical-align: text-bottom;\n");
      out.write(" }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<header>\n");
      out.write("  <h1 class=\"main\"><a href=\"#\" style=\"position: absolute;top:30px;\">yeon HOme</a></h1>\n");
      out.write("  <ul>\n");
      out.write("    <li><a href=\"#\">로그인</a></li>\n");
      out.write("    <li><a href=\"#\">회원가입</a></li>\n");
      out.write("  </ul>\n");
      out.write("</header>\n");
      out.write("<h3>\n");
      out.write("  <span class=\"material-symbols-outlined\">view_list</span> jsp days00\n");
      out.write("</h3>\n");
      out.write("<div>\n");
      out.write("	<a href=\"/jspPro/product/list.ss\">상품 목록보기</a>\n");
      out.write("	<br>\n");
      out.write("\n");
      out.write("  <xmp class=\"code\">\n");
      out.write("   days09.ex05 과제...\n");
      out.write("      \n");
      out.write("   과제....\n");
      out.write(" 1. 상품테이블 / 상품이미지테이블 생성 , 시퀀스 생성\n");
      out.write("--상품테이블\n");
      out.write("create table pd_tbl (\n");
      out.write("    pdCode number(30)  primary key, -- 상품코드\n");
      out.write("    pdName varchar2(50)    not null,    -- 상품명\n");
      out.write("    pdDocu varchar2(100)    not null    -- 상품설명\n");
      out.write(" );\n");
      out.write("-- 상품이미지테이블\n");
      out.write("create table pd_img (\n");
      out.write("    pdNum  number   primary key,        -- 순번\n");
      out.write("    pdCode number(30) ,\n");
      out.write("    origin_imgname varchar2(100) not null,     -- 원래이미지명\n");
      out.write("    file_imgname  varchar2(100)  not null,       -- 파일이미지명\n");
      out.write("    constraint pdCode foreign key(pdCode) references pd_tbl(pdCode) -- 상품코드\n");
      out.write(" );\n");
      out.write("--상품 + 상품이미지 테이블\n");
      out.write(" create table tbl_product (\n");
      out.write("    pdCode number(30)  primary key,     -- 상품코드\n");
      out.write("    pdNum  number   primary key,        -- 순번\n");
      out.write("    file_imgname  varchar2(100)  not null,       -- 파일이미지명 \n");
      out.write("    origin_imgname varchar2(100) not null,     -- 원래이미지명\n");
      out.write("    filelength \n");
      out.write("        \n");
      out.write(" );\n");
      out.write(" -- 시퀀스\n");
      out.write(" create sequence seq_imgnum ; --순번\n");
      out.write(" create sequence seq_codenum; --상품코드   \n");
      out.write(" \n");
      out.write(" mvc 비슷하게 개념...\n");
      out.write("   \n");
      out.write("   실습)\n");
      out.write("   product 패키지\n");
      out.write("      ㄴ ProductDTO.java\n");
      out.write("      ㄴ productDAO.java\n");
      out.write("      ㄴ productServlet.java\n");
      out.write("      ㄴ UploadServlet_02.java\n");
      out.write("      \n");
      out.write("   product 폴더\n");
      out.write("      ㄴ ex01_list.jsp			list.ss\n");
      out.write("      ㄴ ex01_write.jsp			write.ss\n");
      out.write("      ㄴ ex01_update.jsp		update.ss\n");
      out.write("    \n");
      out.write("     [각 팀의 과제]\n");
      out.write("    상품코드\n");
      out.write("    상품명\n");
      out.write("    상품설명\n");
      out.write("    \n");
      out.write("    상품이미지\n");
      out.write("    상품이미지\n");
      out.write("    상품이미지\n");
      out.write("	    :\n");
      out.write("	[상품등록]    \n");
      out.write("	\n");
      out.write("		상품테이블\n");
      out.write("	상품코드(PK)\n");
      out.write("	상품명\n");
      out.write("	상품설명\n");
      out.write("	\n");
      out.write("		상품이미지테이블\n");
      out.write("	순번(PK)\n");
      out.write("	상품코드(FK)\n");
      out.write("	원래이미지명  a.gif\n");
      out.write("	파일이미지명  a(1).gif             \n");
      out.write("  </xmp>  \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
